// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzBrl3R5G0SnyZMaya_RbXHRo53F9dvY',
    appId: '1:399081121182:web:26dc9181b778e417d8e28f',
    messagingSenderId: '399081121182',
    projectId: 'record-app-466923',
    authDomain: 'record-app-466923.firebaseapp.com',
    storageBucket: 'record-app-466923.firebasestorage.app',
    measurementId: 'G-KXGSGRCP92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9bjZshqJVGenPEmx-TDj0e99Yn59TImw',
    appId: '1:399081121182:android:5582157686abac8ed8e28f',
    messagingSenderId: '399081121182',
    projectId: 'record-app-466923',
    storageBucket: 'record-app-466923.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzBrl3R5G0SnyZMaya_RbXHRo53F9dvY',
    appId: '1:399081121182:web:ebf87973f2d1aa4dd8e28f',
    messagingSenderId: '399081121182',
    projectId: 'record-app-466923',
    authDomain: 'record-app-466923.firebaseapp.com',
    storageBucket: 'record-app-466923.firebasestorage.app',
    measurementId: 'G-T2SC7Y378W',
  );
}
